export const Users = [
  {
    id: 1,
    profilePicture: "/assets/images/profile/001.jpg",
    username: "John Doe",
    isOnline: true,
  },
  {
    id: 2,
    profilePicture: "/assets/images/profile/002.jpg",
    username: "Christiano Ronaldo",
    isOnline: false,
  },
  {
    id: 3,
    profilePicture: "/assets/images/profile/003.jpg",
    username: "Roberto Carlos",
    isOnline: true,
  },
  {
    id: 4,
    profilePicture: "/assets/images/profile/004.jpg",
    username: "Tom Cruise",
    isOnline: false,
  },
  {
    id: 5,
    profilePicture: "/assets/images/profile/005.jpg",
    username: "Jeniffer Lopez",
    isOnline: false,
  },
  {
    id: 6,
    profilePicture: "/assets/images/profile/006.jpg",
    username: "Madonna",
    isOnline: true,
  },
  {
    id: 7,
    profilePicture: "/assets/images/profile/007.jpg",
    username: "Michael Jackson",
    isOnline: true,
  },
];

export const Posts = [
  {
    id: 1,
    description: "post 1 description",
    picture: "/assets/images/post/001.jpg",
    date: "5 mins ago",
    userId: 1,
    likeCount: 32,
    commentCount: 9,
  },
  {
    id: 2,
    picture: "/assets/images/post/002.jpg",
    date: "15 mins ago",
    userId: 2,
    likeCount: 2,
    commentCount: 1,
  },
  {
    id: 3,
    description: "post 3 description",
    picture: "/assets/images/post/003.jpg",
    date: "1 hour ago",
    userId: 3,
    likeCount: 61,
    commentCount: 2,
  },
  {
    id: 4,
    picture: "/assets/images/post/004.jpg",
    date: "4 hours ago",
    userId: 4,
    likeCount: 7,
    commentCount: 3,
  },
  {
    id: 5,
    picture: "/assets/images/post/005.jpg",
    date: "5 hours ago",
    userId: 5,
    likeCount: 23,
    commentCount: 5,
  },
  {
    id: 6,
    picture: "/assets/images/post/006.jpg",
    date: "1 day ago",
    userId: 6,
    likeCount: 44,
    commentCount: 6,
  },
  {
    id: 7,
    description: "post 7 description",
    picture: "/assets/images/post/007.jpg",
    date: "2 days ago",
    userId: 7,
    likeCount: 52,
    commentCount: 3,
  },
  {
    id: 8,
    picture: "/assets/images/post/008.jpg",
    date: "3 days ago",
    userId: 1,
    likeCount: 15,
    commentCount: 1,
  },
  {
    id: 9,
    description: "post 9 description",
    picture: "/assets/images/post/009.jpg",
    date: "5 days ago",
    userId: 2,
    likeCount: 11,
    commentCount: 2,
  },
  {
    id: 10,
    picture: "/assets/images/post/010.jpg",
    date: "1 week ago",
    userId: 3,
    likeCount: 104,
    commentCount: 12,
  },
];
